from instaclient import InstaClient
from instaclient.errors import *

USERNAME = 'cricetonzi'
PASSWORD = 'samuele222002'

client = InstaClient(driver_path='c:\dev\instapy\\bin\chromedriver.exe')

try:
    client.login(username=USERNAME, password=PASSWORD) # Go through Login Procedure
except VerificationCodeNecessary:
    # This error is raised if the user has 2FA turned on.
    code = input('Enter the 2FA security code generated by your Authenticator App or sent to you by SMS')
    client.input_verification_code(code)
except SuspisciousLoginAttemptError as error:
    # This error is reaised by Instagram
    if error.mode == SuspisciousLoginAttemptError.EMAIL:
        code = input('Enter the security code that was sent to you via email: ')
    else:
        code = input('Enter the security code that was sent to you via SMS: ')
    client.input_security_code(code)