from getpass import getpass
from saveData import BotData
from instaclient import InstaClient
from instaclient.errors import *

USERNAME = 'cricetonzi'
PASSWORD = 'samuele222002'


class Bot:
	PATH = 'c:\dev\instapy\\bin\chromedriver.exe'
	data: BotData = BotData()
	client = InstaClient(driver_path='c:\dev\instapy\\bin\chromedriver.exe')

	def __init__(self):
		try:
				self.client.login(username=USERNAME, password=PASSWORD) # Go through Login Procedure
		except VerificationCodeNecessary:
				# This error is raised if the user has 2FA turned on.
				code = input('Enter the 2FA security code generated by your Authenticator App or sent to you by SMS')
				self.client.input_verification_code(code)
		except SuspisciousLoginAttemptError as error:
				# This error is reaised by Instagram
				if error.mode == SuspisciousLoginAttemptError.EMAIL:
						code = input('Enter the security code that was sent to you via email: ')
				else:
						code = input('Enter the security code that was sent to you via SMS: ')
				self.client.input_security_code(code)

	def sendMessage(self, username: str, message: str):
		pass

	def searchHashtag(self, hashtag: str):
		pass

	def searchUser(self, username: str):
		pass

	def getFollowednumber(self):
		pass

	def addFollowedToList(self):
		followers = self.client.get_following(user='nascecresceignora', count=500)
		
		for i in followers[0]:
			self.data.addFound(i.username +'\n')
   
		self.data.save()


	def addFollowersToList(self):
		pass

		self.scrape_followers()